export const APPLY_STATUS = {
  NOTHING: 'NOTHING',
  WAITING: 'APPLY',
  RECEIVED: 'APPLY_AND_OFFER',
};

export const APPLICATION_STATUS = {
  EXPIRED: 'EXPIRED',
  CLICKED: 'CLICKED',
  UNCLICKED: 'UNCLICKED',
};
