export const STEP = {
  USER_TYPE: 0,
  PERSONAL_INFO: 1,
  PHONE_NUMBER_VERIFICATION: 2,
  DESIGNER: {
    SHOP_INFO: 4,
    PROFILE: 5,
    DESIGNER_INFO: 6,
    OPEN_CHAT_LINK: 7,
  },
  MODEL: {
    PREFER_REGION: 3,
  },
};

export const TOTAL_STEP = {
  DESIGNER_VIEW: 6,
  MODEL_VIEW: 3,
};
